# This is a basic workflow to help you get started with Actions
name: fetrching

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform_actions:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: set up terraform hasicorp
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      - name: terraform init
        run: |

      - name: Fetch Instance ID and StatusCheck
        run: |
          # Run the AWS CLI command to describe instances and output JSON
          instances_json=$(aws ec2 describe-instances \
            --filters "Name=instance-state-name,Values=running" \
            --query 'Reservations[*].Instances[*].{Instance:InstanceId,StatusChecks:StatusChecks[0].Status}' \
            --output json)

          # Print the JSON output
          echo "Instances: $instances_json"

          # Set the JSON output as an environment variable for use in subsequent steps
          # echo "INSTANCES_JSON=$instances_json" >> $GITHUB_ENV
