name: testing

on:
  workflow_dispatch:

jobs:
  terraform_actions:
    name: terraform
    runs-on: ubuntu-latest
    outputs:
      # Declare the output variable to store the EC2 IPs
      id: ec2_ips
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: set up terraform hasicorp
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      - name: terraform init
        run: terraform init

      - name: Get EC2 IPs
        id: get_ec2_ips
        run: |
          # Run Terraform commands to get the EC2 IPs
          ec2_ips=$(terraform output -json ec2_ips)
          echo "::set-output name=ec2_ips::$ec2_ips"

# Define a new job to use the EC2 IPs
  display_ips:
    name: Display EC2 IPs
    runs-on: ubuntu-latest
    needs: terraform_actions
    steps:
      - name: Display IPs
        run: |
          # Access the output variable from the previous job
          ec2_ips="${{ needs.terraform_actions.outputs.ec2_ips }}"
          echo "EC2 IPs: $ec2_ips"
