name: fetch-ec2-ips

on:
  workflow_dispatch:
  
jobs:
  fetch-ec2-ips:
    name: Fetch EC2 IPs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"

      - name: Fetch EC2 IPs
        id: fetch-ips
        run: |
          aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text > ec2_ips.txt
          echo "::set-output name=ips::$(cat ec2_ips.txt)"
    
      - name: Set IPs as output
        run: |
          for ip in ${{ steps.fetch-ips.outputs.ips }}; do
            echo "EC2 IP: $ip"
          done  # This step is just for confirmation, you can remove it if not needed
        env:
          EC2_IPS: ${{ steps.fetch-ips.outputs.ips }}
